# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
        path: ~/api/
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew
      env: 
        pet_app_jwtSecret: WZ99DVSI626r59/+zx4pSZGH2UfrIajxy1fEnM6lWsU=
        pet_app_jwtExpirationMs: 86400000 
        spring.data.mongodb.uri: mongodb+srv://dbUser:dbPetPassword@pet-cluster-klr51.mongodb.net/Pet-Database?retryWrites=true&w=majority
